'use client';
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./nextjs-portfolio/public/assets/models/CreativesKa3D.glb --transform 
Files: ./nextjs-portfolio/public/assets/models/CreativesKa3D.glb [33.99MB] > CreativesKa3D-transformed.glb [1.63MB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF, useFrame } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/assets/models/CreativesKa3D-transformed.glb')
  
  // Add subtle animation to the model
  useFrame((state) => {
    if (group.current) {
      group.current.rotation.y = Math.sin(state.clock.elapsedTime * 0.15) * 0.05
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.temp.geometry} material={materials['Material.001']} position={[0, 3.82, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[8.1, 8.906, 7.595]} />
      <mesh geometry={nodes.temp001.geometry} material={materials['Material.002']} position={[-5.526, 1.178, 3.73]} rotation={[1.635, 0.001, -2.365]} scale={[2.057, 1.475, 1.896]} />
      <mesh geometry={nodes.temp002.geometry} material={materials['Material.003']} position={[-2.774, 0.78, -3.408]} rotation={[1.538, -0.013, -0.672]} />
      <mesh geometry={nodes.temp004.geometry} material={materials['Material.006']} position={[-0.302, 0.713, -4.312]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.temp005.geometry} material={materials['Material.007']} position={[-4.272, 0.772, -2.56]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.temp008.geometry} material={materials['Material.011']} position={[-0.269, 0.568, -0.993]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0.089, -0.684, -7.447]} scale={[5.92, 4.564, 6.569]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.body_2} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.body} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['fabric.001']} position={[0.031, 0.203, -7.33]} rotation={[0, 0, -Math.PI / 2]} scale={[5.966, 5.833, 2]} />
      <mesh geometry={nodes.Text.geometry} material={materials.Material} position={[-4.629, 2.754, -7.307]} rotation={[1.563, 0, 0]} scale={[1.429, 0.996, 1.14]} />
      <mesh geometry={nodes.root003.geometry} material={materials['Material_542.001']} position={[0, 0, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={[0.003, 0.002, 0.002]} />
    </group>
  )
}

useGLTF.preload('/assets/models/CreativesKa3D-transformed.glb')
